<?php

/**
 * @file
 * Site settings shared by every environment.
 *
 * This file is tracked in Git and must not contain credentials. Database
 * connections and other environment-specific values come from
 * settings.ddev.php (generated by DDEV) or settings.local.php (see
 * ../example.settings.local.php), neither of which is tracked.
 *
 * See default.settings.php for the documentation of every setting.
 */

$databases = [];

$settings['hash_salt'] = getenv('DRUPAL_HASH_SALT') ?: '';
$settings['config_sync_directory'] = '../config/sync';
$settings['update_free_access'] = FALSE;
$settings['container_yamls'][] = $app_root . '/' . $site_path . '/services.yml';
$settings['file_scan_ignore_directories'] = [
  'node_modules',
  'bower_components',
];
$settings['entity_update_batch_size'] = 50;
$settings['entity_update_backup'] = TRUE;
$settings['state_cache'] = TRUE;
$settings['migrate_node_migrate_type_classic'] = FALSE;

// Settings managed by DDEV.
if (getenv('IS_DDEV_PROJECT') == 'true' && file_exists(__DIR__ . '/settings.ddev.php')) {
  include __DIR__ . '/settings.ddev.php';
}

// Local overrides, e.g. database credentials outside DDEV.
if (file_exists(__DIR__ . '/settings.local.php')) {
  include __DIR__ . '/settings.local.php';
}
