#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    wudo-demo-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^wudo-demo\.ddev\.site$`)
      
      service: "wudo-demo-web-80"
      tls: false
      # middlewares:
      #   - "wudo-demo-redirectHttps"
    wudo-demo-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^wudo-demo\.ddev\.site$`)
      
      service: "wudo-demo-web-8025"
      tls: false
      # middlewares:
      #   - "wudo-demo-redirectHttps"
    wudo-demo-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^wudo-demo\.ddev\.site$`)
      
      service: "wudo-demo-xhgui-80"
      tls: false
      # middlewares:
      #   - "wudo-demo-redirectHttps"
    
    
    
    wudo-demo-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^wudo-demo\.ddev\.site$`)
      
      service: "wudo-demo-web-80"
      
      tls: true
      
    wudo-demo-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^wudo-demo\.ddev\.site$`)
      
      service: "wudo-demo-web-8025"
      
      tls: true
      
    
    wudo-demo-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^wudo-demo\.ddev\.site$`)
      
      service: "wudo-demo-xhgui-80"
      
      tls: true
      
    

  middlewares:
    wudo-demo-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    wudo-demo-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-wudo-demo-web:80
        
    wudo-demo-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-wudo-demo-web:8025
        
    
    
    wudo-demo-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-wudo-demo-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/wudo-demo.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/wudo-demo.key